name: Go CI

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: [ master ]

jobs:

  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...

  go-linter:
    name: Go Linter
    runs-on: ubuntu-latest
    steps:
    - name: go1.15 linter
      uses: shoukoo/golang-pipeline/go1.15/linter@master
      with:
        GOLINT: on
        GOLINTPATH: .
        MISSPELL: off
