name: Release Go Binaries

on: 
  release:
    types: [created]

jobs:
  releases-matrix:
    name: github-assets-uploader
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v2

    - name: Set APP_VERSION env
      run: echo ::set-env name=APP_VERSION::$(basename ${GITHUB_REF})
    - name: Set BUILD_TIME env
      run: echo ::set-env name=BUILD_TIME::$(date)
    - name: Environment Printer
      uses: managedkaos/print-env@v1.0

    - uses: wangyoucao577/go-release-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://golang.org/dl/go1.15.3.linux-amd64.tar.gz"
        project_path: "./cmd/github-assets-uploader"
        binary_name: github-assets-uploader
        build_flags: -v
        ldflags: -X "github.com/wangyoucao577/assets-uploader/util/appversion.appVersion=${{ env.APP_VERSION }}" -X "github.com/wangyoucao577/assets-uploader/util/appversion.buildTime=${{ env.BUILD_TIME }}" -X github.com/wangyoucao577/assets-uploader/util/appversion.gitCommit=${{ github.sha }} -X main.gitRef=${{ github.ref }}

        

